pipeline {
  agent {
    kubernetes {
    // This is a YAML representation of the Pod, to allow setting any values not supported as fields.
      yamlFile 'k8s/aws-cli.yaml' // Declarative agents can be defined from YAML.
    }
  }
       stages {

         stage('check version') {
           steps {
             ansiColor('xterm') {
               container("aws-cli") {
                 sh 'aws --version'
                 sh 'aws sts get-caller-identity'
               }
             }
           }
         }
       }
     }
